# Generated by Django 2.2.1 on 2019-06-03 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190531_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='descrition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.Category'),
        ),
    ]
